Repository crew-z/crewz-admin, pull requests merged in 2023-05, with the labels that each got.

#12 feat: backend 환경세팅, SwaggerConfig 생성, 카테고리 추가 기능 구현
  crewz-admin/build.gradle
  crewz-admin/src/main/java/crewz/admin/crewzadmin/configuration/MvcConfiguration.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/configuration/SwaggerConfig.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/CategoryInfoController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestCategoryInfoDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/CategoryInfo.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/CategoryInfoRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/CategoryInfoManager.java
  crewz-admin/src/main/resources/application.properties
Labels: backend

#17 feat: [대시보드] front-end Views 파일 템플릿 수정
  crewz-admin-front/src/App.vue
  crewz-admin-front/src/assets/img/club.svg
  crewz-admin-front/src/assets/img/member.svg
  crewz-admin-front/src/components/components/Header.vue
  crewz-admin-front/src/views/AdminDashboard.vue
  crewz-admin-front/vue.config.js
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/CategoryInfoController.java
Labels: frontend

#19 feat: 카테고리 화면 추가 및 등록 기능 구현
  crewz-admin-front/package-lock.json
  crewz-admin-front/package.json
  crewz-admin-front/src/assets/assets/animate.css
  crewz-admin-front/src/assets/assets/img/user.jpg
  crewz-admin-front/src/assets/assets/img/user1.png
  crewz-admin-front/src/assets/assets/img/user2.png
  crewz-admin-front/src/assets/assets/img/user3.png
  crewz-admin-front/src/assets/assets/img/user4.png
  crewz-admin-front/src/assets/assets/img/user5.png
  crewz-admin-front/src/assets/assets/logo.png
  crewz-admin-front/src/assets/assets/logo/google-logo.svg
  crewz-admin-front/src/assets/assets/logo/logo.svg
  crewz-admin-front/src/assets/assets/logo/windzo-logo-dark.png
  crewz-admin-front/src/assets/assets/logo/windzo-logo-light.png
  crewz-admin-front/src/assets/assets/sass/app.windzo.scss
  crewz-admin-front/src/assets/assets/sass/css/windzo.css
  crewz-admin-front/src/assets/assets/sass/css/windzo.css.map
  crewz-admin-front/src/assets/assets/tailwind.css
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/components/components/Alert.vue
  crewz-admin-front/src/components/components/AppAccordion.vue
  crewz-admin-front/src/components/components/Dropdown.vue
  crewz-admin-front/src/components/components/Footer.vue
  crewz-admin-front/src/components/components/Header.vue
  crewz-admin-front/src/components/components/MenuAccordion.vue
  crewz-admin-front/src/components/components/Sidebar.vue
  crewz-admin-front/src/components/components/Tables.vue
  crewz-admin-front/src/components/components/modal.vue
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/components/AddCategory.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/CategoryInfoController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/PagingUtil.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestCategoryInfoDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestPageDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseCategoryDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/CategoryInfo.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/CategoryInfoManager.java
  crewz-admin/src/main/resources/application.properties
Labels: frontend, backend

#23 feat: entity merge
  .gitignore
  README.md
  crewz-admin-front/package-lock.json
  crewz-admin-front/package.json
  crewz-admin-front/src/App.vue
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/AdminDashboard.vue
  crewz-admin-front/src/views/components/AdminAlert.vue
  crewz-admin-front/vue.config.js
  crewz-admin/src/main/java/crewz/admin/crewzadmin/CrewzAdminApplication.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubDashboardController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubApplyDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubDashboardDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubInfoDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/Club.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/ClubApply.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/ClubInfo.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/User.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubDashboardRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubDashboardService.java
  crewz-admin/src/main/resources/application.properties
Labels: backend

#24 feat: spring-security 적용
  crewz-admin/build.gradle
  crewz-admin/src/main/java/crewz/admin/crewzadmin/CrewzAdminApplication.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/configuration/WebSecurityConfig.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/LoginController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestAdminDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/AdminUser.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/AdminRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/AdminDetailService.java
  crewz-admin/src/main/resources/application.properties
Labels: backend
