Repository crew-z/crewz-admin, pull requests merged in 2023-06, with the labels that each got.

#27 feat: 동아리 리스트 페이지
  crewz-admin-front/src/App.vue
  crewz-admin-front/src/components/AdminModal.vue
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/AdminDashboard.vue
  crewz-admin-front/src/views/components/AddCategory.vue
  crewz-admin-front/src/views/components/ClubTable.vue
  crewz-admin-front/vue.config.js
  crewz-admin/src/main/java/crewz/admin/crewzadmin/configuration/CustomErrorController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/configuration/WebSecurityConfig.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/CategoryInfoController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseClubDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubService.java
Labels: frontend, backend

#33 feat: 동아리별 회원수 차트
  crewz-admin-front/src/views/components/AdminClubInfo.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubDashboardController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubDashboardDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubDashboardRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubDashboardService.java
Labels: frontend, backend

#32 feat: [대시보드] front-back 연결
  crewz-admin-front/src/views/AdminDashboard.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseDashboardDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/Subsidy.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/BoardCategoryRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/SubsidyRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/UserRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/DashboardService.java
Labels: frontend, backend

#39 feat: Admin 리스트 생성
  crewz-admin-front/package-lock.json
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/components/ManageAdmin.vue
  crewz-admin-front/src/views/components/WithdrawalUser.vue
  crewz-admin/.gitignore
Labels: frontend

#41 feat: [대시보드] front-end 변경사항 및 그래프 작업 완료
  crewz-admin-front/src/assets/img/operating.svg
  crewz-admin-front/src/views/AdminDashboard.vue
  crewz-admin/.gitignore
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/DashboardController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseDashboardDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/Club.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/BoardCategoryRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/SubsidyRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubService.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/DashboardService.java
Labels: frontend, backend

#47 feat: [사이드바] 로고 변경
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubService.java
Labels: frontend

#50 feat: 동아리별 대시보드 개발
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/components/AddCategory.vue
  crewz-admin-front/src/views/components/AdminClubInfo.vue
  crewz-admin-front/src/views/components/ClubTable copy.vue
  crewz-admin-front/src/views/components/ClubTable.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubDashboardController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubMemberListDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubDashboardRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubDashboardService.java
  crewz-admin/src/main/resources/static/img/club.bb572e8e.svg
  crewz-admin/src/main/resources/static/img/logo.d71977e5.svg
  crewz-admin/src/main/resources/static/img/member.2a1e3d73.svg
  crewz-admin/src/main/resources/static/js/app.js
Labels: frontend, backend

#51 feat: 동아리 지원금, 동아리 폐부 기능
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/views/components/ClubTable.vue
  crewz-admin-front/src/views/components/ManageAdmin.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubSubsidyController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestClubSubsidyDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/Club.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/Subsidy.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ResponseClubSubsidyInterface.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/SubsidyRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubService.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubSubsidyService.java
Labels: frontend, backend

#56 fix: [대시보드] 분기별 생성 삭제 테이블 에러 해결
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/DashboardService.java
Labels: backend

#59 feat: 지원금 등록 기능 구현
  crewz-admin-front/src/components/AdminModal.vue
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/components/AddCategory.vue
  crewz-admin-front/src/views/components/AdminButton.vue
  crewz-admin-front/src/views/components/AdminModal.vue
  crewz-admin-front/src/views/components/ClubTable.vue
  crewz-admin-front/src/views/components/ManageAdmin.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubSubsidyController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/AdminListDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubListDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubSubsidyDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/Subsidy.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubApplyRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/SubsidyRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubSubsidyService.java
  crewz-admin/src/main/resources/static/js/app.js
Labels: frontend, backend

#60 feat: axios 함수화
  crewz-admin-front/package-lock.json
  crewz-admin-front/package.json
  crewz-admin-front/src/api/clubapply.js
  crewz-admin-front/src/api/core/request.js
  crewz-admin-front/src/api/post.js
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/main.js
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/components/ClubApplyTable.vue
  crewz-admin-front/src/views/components/ClubTable copy.vue
  crewz-admin-front/src/views/components/ClubTable.vue
Labels: frontend, backend

#63 feat: [Sidebar] 로그인 유저이름, 로그아웃 틀 제작 & axios 구조 변경
  crewz-admin-front/src/api/dashboard.js
  crewz-admin-front/src/api/sidebar.js
  crewz-admin-front/src/assets/logo/logo-admin.svg
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/views/AdminDashboard.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/DashboardService.java
Labels: frontend

#64 refactor: axios 함수화, 지원금 등록 수정
  crewz-admin-front/src/api/club.js
  crewz-admin-front/src/api/clubapply.js
  crewz-admin-front/src/api/core/request.js
  crewz-admin-front/src/views/components/ClubApplyTable.vue
  crewz-admin-front/src/views/components/ClubTable.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/Club.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/AdminRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/AdminUserRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubSubsidyService.java
  crewz-admin/src/main/resources/static/js/app.js
  crewz-admin/src/main/resources/static/js/chunk-vendors.js
Labels: frontend, backend

#65 feat: Spring Security + JWT 적용
  crewz-admin-front/src/App.vue
  crewz-admin-front/src/api/core/request.js
  crewz-admin-front/src/api/login.js
  crewz-admin-front/src/api/manageadmin.js
  crewz-admin-front/src/api/manageuser.js
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/store/index.js
  crewz-admin-front/src/util/validation.js
  crewz-admin-front/src/views/components/AdminLogin.vue
  crewz-admin-front/src/views/components/ManageAdmin.vue
  crewz-admin-front/src/views/components/WithdrawalUser.vue
  crewz-admin/build.gradle
  crewz-admin/src/main/java/crewz/admin/crewzadmin/configuration/WebSecurityConfig.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/LoginController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/jwt/JwtAuthenticationFilter.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/jwt/TokenProvider.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestAdminDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseLoginDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/entity/AdminUser.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/AdminRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/repository/ClubInfoRepository.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/AdminDetailService.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/AdminInfoService.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/UserService.java
  crewz-admin/src/main/resources/application.properties
Labels: frontend, backend

#67 feat: 로그아웃 기능 구현
  crewz-admin-front/src/api/sidebar.js
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/views/components/WithdrawalUser.vue
Labels: frontend

#73 refactor: dto naming Vue footer 고정
  crewz-admin-front/src/assets/tailwind.css
  crewz-admin-front/src/components/AdminFooter.vue
  crewz-admin-front/src/components/AdminSidebar.vue
  crewz-admin-front/src/router/index.js
  crewz-admin-front/src/views/AdminDashboard.vue
  crewz-admin-front/src/views/components/AddCategory.vue
  crewz-admin-front/src/views/components/AdminClubInfo.vue
  crewz-admin-front/src/views/components/ClubApplyTable.vue
  crewz-admin-front/src/views/components/ClubTable.vue
  crewz-admin-front/src/views/components/ManageAdmin.vue
  crewz-admin-front/src/views/components/WithdrawalUser.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubDashboardController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubSubsidyController.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ClubApplyDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestClubDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/RequestClubInfoDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseAdminListDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseClubDashboardDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseClubListDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseClubMemberListDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/model/dto/ResponseClubSubsidyDto.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubDashboardService.java
  crewz-admin/src/main/java/crewz/admin/crewzadmin/service/ClubSubsidyService.java
  crewz-admin/src/main/resources/static/js/app.js
  crewz-admin/src/main/resources/static/js/chunk-vendors.js
Labels: frontend, backend

#82 fix: ClubApply 정렬 최신순으로 변경
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/ClubController.java
Labels: backend

#83 fix: 일부 컴포넌트 전역 axios 미반영 수정, 반려 실패 오류 수정
  crewz-admin-front/src/api/category.js
  crewz-admin-front/src/api/club.js
  crewz-admin-front/src/api/clubapply.js
  crewz-admin-front/src/views/components/AddCategory.vue
  crewz-admin-front/src/views/components/ClubApplyTable.vue
  crewz-admin-front/src/views/components/ClubTable.vue
  crewz-admin/src/main/java/crewz/admin/crewzadmin/controller/CategoryInfoController.java
Labels: frontend, backend
